package cn.wuaijing.mapper;

import cn.wuaijing.bean.User;
import cn.wuaijing.bean.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    @Delete({
        "delete from users",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    @Insert({
        "insert into users (id, user_name, ",
        "birthday, sex, address, ",
        "d_id)",
        "values (#{id,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{birthday,jdbcType=DATE}, #{sex,jdbcType=CHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{dId,jdbcType=INTEGER})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    @Select({
        "select",
        "id, user_name, birthday, sex, address, d_id",
        "from users",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("cn.wuaijing.mapper.UserMapper.BaseResultMap")
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Dec 06 13:23:08 CST 2020
     */
    @Update({
        "update users",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=DATE},",
          "sex = #{sex,jdbcType=CHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "d_id = #{dId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);

    /**
    * @Description 获取所有的user
    * @Author  wangwei
    * @Date   2020/12/6 13:24
    * @Param
    * @Return
    * @Exception
    *
    */
    public  List<User>  selectAll();


    /**
    * @Description 使用Plugin批量添加用户
    * @Author  wangwei
    * @Date   2020/12/15 19:48
    * @Param
    * @Return
    * @Exception
    *
    */
    public long addUsers(User user);
}